config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'generate', to: 'maze#generate'
  post 'show-path', to: 'maze#show_path'
  root 'maze#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  before_save :serialize_array_fields

  def vertical_walls
    ActiveSupport::JSON.decode(read_attribute(:vertical_walls))
  end

  def horizontal_walls
    ActiveSupport::JSON.decode(read_attribute(:horizontal_walls))
  end

  private

  def serialize_array_fields
    self.vertical_walls   = ActiveSupport::JSON.encode(self.vertical_walls)
    self.horizontal_walls = ActiveSupport::JSON.encode(self.horizontal_walls)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/maze_controller.rb
class MazeController < ApplicationController

  def index
  end

  def generate
    if board_params_invalid?
      @error_msg = t('maze.generate.errors.invalid_params')
      return
    end

    board = Maze::Generator.new(params[:board][:width].to_i, params[:board][:height].to_i).generate
    @maze_presenter = MazePresenter.new(board)
    session[:board] = params[:board]
  rescue SystemStackError => e
    @error_msg = t('maze.generate.errors.system_stack_error')
  rescue exception => e
    @error_msg = t('maze.generate.errors.exception')
  end

  def show_path
    board = Board.where(session[:board].slice(:width, :height)).last(1).last
    @maze_presenter = MazePresenter.new(board)
    @maze_presenter.path = Maze::PathFinder.new(board).solve
  end


  private

  def board_params
    params.require(:board).permit(:width, :height)
  end

  def board_params_invalid?
    params[:board].blank? || params[:board][:width].to_i == 0 || params[:board][:height].to_i == 0
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Maze</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/maze/_board.js.erb
var board = document.getElementById('maze-board');
board.innerHTML = `<%= board.show_as_html %>`;

app/views/maze/generate.js.erb
var alertElement = document.getElementById('alert-error');
alertElement.style.display = 'none';

<% if @error_msg %>

  alertElement.innerHTML = '<%= @error_msg %>';
  alertElement.style.display = 'block';

<% else %>

  <%= render partial:'board', locals: { board: @maze_presenter } %>

  var showPathButton = document.getElementById('btn-show-path');
  showPathButton.style.display = 'block';

<% end %>

app/views/maze/index.html.erb
<h1>Maze generator</h1>

<%= form_tag('generate', method: 'post', remote: true) do %>
  <%= label_tag(:width, 'Width') %>
  <%= text_field_tag(:width, nil, name:'board[width]', onkeyup:'removeNonNumbers(this)', onpaste:'removeNonNumbers(this)') %>
  <%= label_tag(:height, 'Height') %>
  <%= text_field_tag(:height, nil, name: 'board[height]', onkeyup:'removeNonNumbers(this)', onpaste:'removeNonNumbers(this)') %>
  <%= submit_tag("Generate", data: { disable_with: "sending..." }) %>
<% end %>
<div id="alert-error"></div>
<div id="maze-board"></div>
<%= button_to('Show Path', show_path_path, remote: true, id: 'btn-show-path') %>

app/views/maze/show_path.js.erb
<%= render partial:'board', locals: { board: @maze_presenter } %>